[package]
name = "prism"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "30"
winit = "0.30"
pollster = "0.3"
glyphon = "0.12"
crossbeam = "0.8"
image = "0.25"
bytemuck = "1"
thiserror = "2.0.19"
utils = { path = "../utils" }
tracing = "0.1"
weave = { git = "https://github.com/Snowdeenn/weave.git" }

[[example]]
name = "demo"
path = "src/examples/demo.rs"